import { MoreVertical } from 'lucide-react'
import type { MouseEvent } from 'react'
import { Card } from '@/components/ui/card'
import { FileIcon } from '@/components/drive/FileIcon'
import type { FileItem } from '@/data/drive-data'
import { cn } from '@/lib/utils'
export function FileGrid({ files, selectedFileIds = new Set<string>(), onFileContextMenu, onToggleFile }: { files: FileItem[]; selectedFileIds?: Set<string>; onFileContextMenu?: (event: MouseEvent<HTMLElement>, file: FileItem) => void; onToggleFile?: (file: FileItem) => void }) {
  return <div className="grid grid-cols-1 gap-4 min-[400px]:grid-cols-2 md:grid-cols-3 2xl:grid-cols-4">{files.map(file => <Card key={file.id || file.name} draggable onDragStart={event => { event.dataTransfer.setData('text/plain', file.id || ''); event.dataTransfer.effectAllowed = 'move' }} onClick={() => onToggleFile?.(file)} onContextMenu={event => onFileContextMenu?.(event, file)} className={cn('file-card p-4', selectedFileIds.has(file.id || '') && 'file-selected')}><div className="mb-3 flex items-center justify-between"><input aria-label={`Select ${file.name}`} type="checkbox" checked={selectedFileIds.has(file.id || '')} onChange={() => onToggleFile?.(file)} onClick={event => event.stopPropagation()} className="h-4 w-4" /><button className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100" aria-label={`Open ${file.name} menu`} onClick={event => { event.stopPropagation(); onFileContextMenu?.(event, file) }}><MoreVertical size={16} /></button></div><div className="file-card-art"><FileIcon kind={file.kind} className="h-12 w-12 rounded-xl p-2.5" /></div><h3 className="mt-4 truncate text-sm font-semibold" title={file.name}>{file.name}</h3><p className="mt-1 text-[11px] text-slate-500">{file.date}</p><div className="mt-4 flex min-w-0 items-center gap-2 border-t border-slate-100 pt-3 text-[10px] text-slate-500"><span className="h-1.5 w-1.5 shrink-0 rounded-full bg-indigo-400" /><span className="truncate" title={file.access}>{file.accountProvider || file.access}</span></div></Card>)}</div>
}
