import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowUpRight, Cloud, HardDrive, Layers3 } from 'lucide-react'
import { apiFetch, formatBytes } from '@/lib/api'
import { ProviderLogo, providerName } from './ProviderLogo'
import { Card } from '@/components/ui/card'
type Summary = { usedBytes: string; totalBytes: string | null; availableBytes: string | null; accounts: { id: string; provider: string; email: string; usedBytes: string; totalBytes: string | null; status: string }[] }
export function WorkspaceOverview() {
  const [summary, setSummary] = useState<Summary | null>(null), [error, setError] = useState('')
  const load = useCallback(async () => { try { setSummary(await apiFetch<Summary>('/storage/summary')); setError('') } catch { setError('Storage overview is unavailable.'); setSummary(null) } }, [])
  useEffect(() => { void load(); const refresh = () => { void load() }; window.addEventListener('9drive:storage-changed', refresh); return () => window.removeEventListener('9drive:storage-changed', refresh) }, [load])
  const total = Number(summary?.totalBytes ?? 0), used = Number(summary?.usedBytes ?? 0), progress = total ? Math.min(100, used / total * 100) : 0
  return <section className="workspace-overview mt-7" aria-label="Cloud storage overview"><div className="overview-intro"><p className="eyebrow">Your connected workspace</p><h2 className="mt-3 text-2xl font-semibold leading-tight tracking-tight">Everything has<br />a place.</h2><p className="mt-3 text-sm leading-6 text-slate-500">Your files stay in your clouds.<br />Your workspace brings them together.</p><Link to="/settings" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-indigo-600">Manage connections<ArrowUpRight size={16} /></Link></div><Card className="overview-storage p-6"><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-2 text-sm font-semibold"><HardDrive size={17} className="text-indigo-500" />Storage overview</span><Link to="/quota" aria-label="View storage usage"><ArrowUpRight size={17} className="text-slate-400" /></Link></div>{error ? <p role="status" className="mt-5 text-sm text-slate-500">{error} <button onClick={() => void load()} className="underline">Retry</button></p> : <><p className="mt-7 text-3xl font-semibold tracking-tight">{summary ? formatBytes(summary.usedBytes) : '—'}<span className="ml-2 text-xs font-normal text-slate-500">used</span></p><div className="storage-meter mt-5" role="progressbar" aria-label="Storage used" aria-valuenow={Math.round(progress)} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${progress}%` }} /></div><div className="mt-3 flex flex-wrap justify-between gap-2 text-xs text-slate-500"><span>{summary?.availableBytes != null ? `${formatBytes(summary.availableBytes)} available` : 'Capacity not configured'}</span><span>{summary?.totalBytes != null ? `${formatBytes(summary.totalBytes)} total` : ''}</span></div></>}</Card><Card className="overview-connections p-6"><div className="flex items-center gap-2 text-sm font-semibold"><Layers3 size={17} className="text-cyan-600" />Connected clouds</div><div className="mt-5 space-y-4">{['google_drive', 's3', 'dropbox'].map(provider => { const accounts = summary?.accounts.filter(a => a.provider === provider && a.status === 'connected') ?? []; return <div key={provider} className="flex items-center gap-3"><ProviderLogo provider={provider} className="h-8 w-8 rounded-lg [&_svg]:h-4 [&_svg]:w-4" /><span className="flex-1 text-xs font-semibold">{providerName(provider)}</span><span className={`text-xs ${accounts.length ? 'text-emerald-600' : 'text-slate-400'}`}>{!summary ? '—' : accounts.length ? `${accounts.length} connected` : 'Not connected'}</span></div> })}</div><Link className="mt-5 inline-flex items-center gap-1.5 text-xs font-semibold text-indigo-600" to="/provider-health"><Cloud size={14} />View provider health</Link></Card></section>
}
