import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { Activity, ArrowRight, Cloud, Copy, FileText, History, Inbox, RefreshCw, ShieldCheck, SlidersHorizontal, TriangleAlert } from 'lucide-react'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { PageHeader } from '@/components/drive/PageHeader'
import { apiFetch, formatDate } from '@/lib/api'

type Account = { id: string; name: string; provider: string | null; status: string }
type Event = { id: string; action: string; title: string; category: string; createdAt: string; severity: string; name: string | null; bytes: string | null; provider: string | null; file: { id: string | null; name: string; status: string } | null; room: { id: string; name: string; status: string } | null; account: Account | null; source: Account | null; destination: Account | null; details: { label: string; value: string }[] }
type Page = { events: Event[]; nextCursor: string | null; total: number; counts: Record<string, number> }
type Options = { actions: { value: string; label: string; category: string }[]; accounts: Account[] }
const styles: Record<string, { label: string; icon: typeof History; color: string }> = {
  files: { label: 'Files & folders', icon: FileText, color: 'bg-blue-50 text-blue-600' }, replication: { label: 'Replication', icon: Copy, color: 'bg-violet-50 text-violet-600' }, failover: { label: 'Failover', icon: ArrowRight, color: 'bg-amber-50 text-amber-700' }, health: { label: 'Provider health', icon: ShieldCheck, color: 'bg-emerald-50 text-emerald-700' }, delivery: { label: 'Delivery rooms', icon: Inbox, color: 'bg-cyan-50 text-cyan-700' }, providers: { label: 'Connections', icon: Cloud, color: 'bg-indigo-50 text-indigo-600' }, activity: { label: 'Other activity', icon: Activity, color: 'bg-slate-100 text-slate-600' },
}
function localInput(iso: string | null) { if (!iso || !Number.isFinite(Date.parse(iso))) return ''; const d = new Date(iso); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16) }
export function ActivityLogPage() {
  const [params, setParams] = useSearchParams(), key = params.toString()
  const [data, setData] = useState<Page | null>(null), [options, setOptions] = useState<Options | null>(null)
  const [error, setError] = useState(''), [optionError, setOptionError] = useState(''), [loading, setLoading] = useState(true), [loadingMore, setLoadingMore] = useState(false), [live, setLive] = useState(false), [older, setOlder] = useState(false)
  const [from, setFrom] = useState(localInput(params.get('from'))), [to, setTo] = useState(localInput(params.get('to')))
  const [updatedAt, setUpdatedAt] = useState<Date | null>(null)
  const version = useRef(0)
  const loadOptions = useCallback(async () => { try { setOptions(await apiFetch<Options>('/audit-logs/options')); setOptionError('') } catch (e) { setOptionError(e instanceof Error ? e.message : 'Cannot load filter options.') } }, [])
  useEffect(() => { void loadOptions() }, [loadOptions])
  const load = useCallback(async () => {
    const current = ++version.current; setLoading(true); setError(''); setOlder(false)
    try { const result = await apiFetch<Page>(`/audit-logs/timeline?${key}`); if (version.current === current) { setData(result); setUpdatedAt(new Date()) } }
    catch (e) { if (version.current === current) setError(e instanceof Error ? e.message : 'Timeline could not be loaded.') }
    finally { if (version.current === current) setLoading(false) }
  }, [key])
  useEffect(() => { setData(null); setLoadingMore(false); setFrom(localInput(params.get('from'))); setTo(localInput(params.get('to'))); void load(); return () => { version.current++ } }, [load])
  useEffect(() => { if (!live || older || loadingMore) return; const timer = setInterval(() => void load(), 15000); return () => clearInterval(timer) }, [live, older, loadingMore, load])
  async function more() {
    if (!data?.nextCursor || loadingMore || loading) return
    const current = version.current, next = new URLSearchParams(key); next.set('cursor', data.nextCursor); setLoadingMore(true); setError('')
    try { const result = await apiFetch<Page>(`/audit-logs/timeline?${next}`); if (version.current === current) { setData(previous => previous ? { ...result, events: [...previous.events, ...result.events.filter(event => !previous.events.some(old => old.id === event.id))] } : result); setOlder(true) } }
    catch (e) { if (version.current === current) setError(e instanceof Error ? e.message : 'Older events could not be loaded.') }
    finally { if (version.current === current) setLoadingMore(false) }
  }
  function filter(name: string, value: string) { const next = new URLSearchParams(key); next.delete('cursor'); if (value) next.set(name, value); else next.delete(name); if (name === 'category') next.delete('action'); setParams(next) }
  function applyDates(event: FormEvent) { event.preventDefault(); if (from && to && new Date(from) > new Date(to)) { setError('Start time must be before end time.'); return } const next = new URLSearchParams(key); next.delete('cursor'); from ? next.set('from', new Date(from).toISOString()) : next.delete('from'); to ? next.set('to', new Date(to).toISOString()) : next.delete('to'); setParams(next) }
  function recent(hours: number) { const next = new URLSearchParams(key); next.set('from', new Date(Date.now() - hours * 3600000).toISOString()); next.delete('to'); next.delete('cursor'); setParams(next) }
  const selectClass = 'mt-2 h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm'
  const groups: { day: string; events: Event[] }[] = []
  for (const event of data?.events ?? []) { const day = new Date(event.createdAt).toLocaleDateString(undefined, { dateStyle: 'full' }); const last = groups.at(-1); if (last?.day === day) last.events.push(event); else groups.push({ day, events: [event] }) }
  return <>
    <PageHeader title="Cloud storage timeline" description="Follow your files, cloud connections, and background storage activity." actions={<Button variant="outline" disabled={loading || loadingMore} onClick={() => { void load(); void loadOptions() }}><RefreshCw size={16} className={loading ? 'animate-spin' : ''} />Refresh</Button>} />
    <div className="mt-7 flex flex-wrap gap-2"><button onClick={() => filter('category', '')} aria-pressed={!params.get('category')} className={`rounded-full border px-4 py-2 text-xs font-semibold ${!params.get('category') ? 'border-blue-600 bg-blue-600 text-white' : 'border-slate-200 bg-white text-slate-600'}`}>All events</button>{Object.entries(styles).map(([value, style]) => <button key={value} onClick={() => filter('category', value)} aria-pressed={params.get('category') === value} className={`rounded-full border px-4 py-2 text-xs font-semibold ${params.get('category') === value ? 'border-blue-600 bg-blue-600 text-white' : 'border-slate-200 bg-white text-slate-600'}`}>{style.label}</button>)}</div>
    <Card className="mt-5 p-5"><h2 className="flex items-center gap-2 text-sm font-bold"><SlidersHorizontal size={16} />Filter history</h2>{optionError && <p role="alert" className="mt-3 text-sm text-red-600">{optionError} <button className="underline" onClick={() => void loadOptions()}>Retry</button></p>}<div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-xs font-semibold text-slate-500">Event type<select className={selectClass} value={params.get('action') || ''} onChange={e => filter('action', e.target.value)}><option value="">All event types</option>{options?.actions.filter(action => !params.get('category') || action.category === params.get('category')).map(action => <option key={action.value} value={action.value}>{action.label}{action.value === 'FILE_UPLOADED' ? ' (legacy)' : ''}</option>)}</select></label><label className="text-xs font-semibold text-slate-500">Provider<select className={selectClass} value={params.get('provider') || ''} onChange={e => filter('provider', e.target.value)}><option value="">All providers</option><option value="google_drive">Google Drive</option><option value="s3">S3-compatible storage</option><option value="dropbox">Dropbox</option></select></label><label className="text-xs font-semibold text-slate-500">Storage account<select className={selectClass} value={params.get('accountId') || ''} onChange={e => filter('accountId', e.target.value)}><option value="">All accounts</option>{options?.accounts.map(account => <option key={account.id} value={account.id}>{account.name}{account.status !== 'connected' ? ' (disconnected)' : ''}</option>)}</select></label></div>
      <form onSubmit={applyDates} className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end"><label className="flex-1 text-xs font-semibold text-slate-500">From (your local time)<Input type="datetime-local" value={from} onChange={e => setFrom(e.target.value)} className="mt-2" /></label><label className="flex-1 text-xs font-semibold text-slate-500">To (your local time)<Input type="datetime-local" value={to} onChange={e => setTo(e.target.value)} className="mt-2" /></label><Button variant="outline">Apply dates</Button></form><div className="mt-4 flex flex-wrap gap-2"><Button variant="ghost" size="sm" onClick={() => recent(24)}>Last 24 hours</Button><Button variant="ghost" size="sm" onClick={() => recent(168)}>Last 7 days</Button><Button variant="ghost" size="sm" onClick={() => { setFrom(''); setTo(''); setParams({}) }}>Clear filters</Button></div>
    </Card>
    <div className="mt-6 flex flex-wrap items-center justify-between gap-3 text-xs text-slate-500"><p>{data ? `${data.total} matching events · ${data.events.length} shown` : 'Loading history…'}{updatedAt && ` · Updated ${updatedAt.toLocaleTimeString()}`}</p><label className="flex items-center gap-2"><input type="checkbox" checked={live} onChange={e => setLive(e.target.checked)} />Refresh every 15 seconds{live && older ? ' (paused while viewing older events)' : ''}</label></div>
    {error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    {loading && !data ? <Card className="mt-5 p-12 text-center"><RefreshCw className="mx-auto animate-spin text-blue-500" /><p className="mt-3 text-sm" role="status">Loading cloud activity…</p></Card> : data?.events.length === 0 ? <Card className="mt-5 p-12 text-center"><History size={36} className="mx-auto text-slate-400" /><h2 className="mt-4 font-bold">No matching activity</h2><p className="mt-2 text-sm text-slate-500">Try a wider date range or fewer filters. New storage activity will appear here.</p></Card> : groups.map(group => <section key={group.day} className="mt-7"><h2 className="mb-4 text-xs font-bold uppercase tracking-wide text-slate-500">{group.day}</h2><div className="ml-4 border-l border-slate-200 pl-6 sm:pl-8">{group.events.map(event => {
      const style = styles[event.category] || styles.activity, Icon = event.severity === 'error' ? TriangleAlert : style.icon
      return <article key={event.id} className="relative pb-5"><span className={`absolute -left-[41px] top-5 grid h-8 w-8 place-items-center rounded-full border-4 border-slate-50 sm:-left-[49px] ${event.severity === 'error' ? 'bg-red-100 text-red-600' : style.color}`}><Icon size={14} /></span><Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><span className={`inline-block rounded-md px-2 py-1 text-[10px] font-bold uppercase tracking-wide ${style.color}`}>{style.label}</span><h3 className="mt-2 text-sm font-bold">{event.title}</h3>{event.name && <p className="mt-1 break-words text-sm text-slate-600">{event.name}</p>}</div><time dateTime={event.createdAt} title={formatDate(event.createdAt)} className="shrink-0 text-xs text-slate-400">{new Date(event.createdAt).toLocaleTimeString()}</time></div>
        {(event.source || event.destination) && <div className="mt-4 flex flex-wrap items-center gap-2 rounded-lg bg-slate-50 px-3 py-2 text-xs"><span>{event.source?.name || 'Original storage'}</span><ArrowRight size={14} /><span>{event.destination?.name || event.account?.name || 'Storage destination'}</span></div>}
        <div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs text-slate-500">{event.account && <span>{event.account.name}{event.account.status !== 'connected' ? ` · ${event.account.status}` : ''}</span>}{event.provider && <span>{event.provider === 'dropbox' ? 'Dropbox' : event.provider === 'google_drive' ? 'Google Drive' : 'S3 storage'}</span>}{event.room && event.file && <span>Room: {event.room.name}</span>}</div>
        {event.details.length > 0 && <details className="mt-4 text-xs"><summary className="cursor-pointer font-semibold text-slate-500">Event details</summary><dl className="mt-3 grid gap-2 sm:grid-cols-[160px_1fr]">{event.details.map((detail, i) => <div key={i} className="contents"><dt className="font-medium text-slate-500">{detail.label}</dt><dd className="break-words text-slate-700">{detail.value}</dd></div>)}</dl></details>}
        {(event.file?.status === 'active' || event.room && !['deleted', 'removed'].includes(event.room.status)) && <div className="mt-4 flex flex-wrap gap-4 text-xs font-semibold text-blue-600">{event.file?.status === 'active' && <Link to={`/all-files?q=${encodeURIComponent(event.file.name)}`}>Find in My Files</Link>}{event.room && !['deleted', 'removed'].includes(event.room.status) && <Link to="/delivery-rooms">Open delivery rooms</Link>}</div>}
      </Card></article>
    })}</div></section>)}
    {data?.nextCursor && <div className="mt-3 pb-5 text-center"><Button variant="outline" onClick={() => void more()} disabled={loading || loadingMore}>{loadingMore ? 'Loading…' : 'Load older events'}</Button></div>}
  </>
}
